from pygame import Vector2

# Window
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600

# Player
PLAYER_SIZE = Vector2(39, 48)
PLAYER_BASE_SPEED = 0.1
PLAYER_MOVE_FRAMES = 8
PLAYER_ATTACK_FRAMES = 6

# Enemy
ENEMY_SIZE = Vector2(48, 48)
ENEMY_BASE_SPEED = 0.1

# Movement
UP = 1
LEFT = 2
DOWN = 3
RIGHT = 4