from pygame import Vector2

# Window
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600
WINDOW_CENTER = (WINDOW_WIDTH / 2, WINDOW_HEIGHT / 2)

# Player
PLAYER_BASE_SPEED = 5
PLAYER_MOVE_FRAMES = 8
PLAYER_ATTACK_FRAMES = 6

# Enemy
ENEMY_SIZE = Vector2(48, 48)
ENEMY_BASE_SPEED = 5

# Movement
UP = 1
LEFT = 2
DOWN = 3
RIGHT = 4